apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app 
    spec:
      containers:
      - name: spring-app
        image: setiaamit/hello-kaniko:0.3
        ports:
        - containerPort: 8080
